# Generated by Django 3.2.20 on 2023-08-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='n',
            field=models.IntegerField(default=1543),
            preserve_default=False,
        ),
    ]
