# Generated by Django 3.2.20 on 2023-08-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_file_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('local_path', models.CharField(max_length=255)),
                ('access_rights', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
