# Generated by Django 3.2.20 on 2023-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_auto_20230809_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonurl',
            name='owner',
            field=models.CharField(default='avborovets', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
