# Generated by Django 3.2.20 on 2023-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_commonurl_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonurl',
            name='owner',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
